### ISSUE TITLE
Not able to run this plugin

### ISSUE THREAD

**Issue by mxmkmarquette** [Jazz-Man/wp-performance#3]
is there anyway to run/load this plugin?

**Comment by Jazz-Man** [comment]
Hi @mxmkmarquette 
Sorry for the long wait for an answer

This plugin can be installed only if your project uses composer and all dependencies are installed from composer.
This plugin has several external dependencies on several external php libraries:

- [https://github.com/Jazz-Man/autoload-interface](https://github.com/Jazz-Man/autoload-interface)
- [https://github.com/Jazz-Man/custom-post-type](https://github.com/Jazz-Man/custom-post-type)
- [https://github.com/Jazz-Man/wp-app-config](https://github.com/Jazz-Man/wp-app-config)
- [https://github.com/Jazz-Man/wp-db-pdo](https://github.com/Jazz-Man/wp-db-pdo)

These libraries in turn also have some external dependencies and the plugin was developed as part of the ecosystem on [Bedrock](https://roots.io/bedrock/) and it's all included in this [wp-boilerplate](https://github.com/Jazz-Man/wp-boilerplate).

It is not in my plans to change the process of installing my plugins for standard WordPress installations
